### ISSUE TITLE
Domoticz crashes when manually deleting, adding or renaming devices

### ISSUE THREAD

**Issue by siether** [enesbcs/Shelly_MQTT#67] opened 2020-08-08 09:16 UTC
When editing a device: adding, deleting or renaming domoticz crashes every time.

This is my log at the moment it crashes:

2020-08-08 11:13:09.481  Error: Domoticz(pid:383361, tid:383364('PluginMgr')) received fatal signal 11 (Segmentation fault)
2020-08-08 11:13:09.481  Error: siginfo address=0x5d981, address=0x7f1d852bd24b
2020-08-08 11:13:09.489  Error: Failed to start gdb, will use backtrace() for printing stack frame

2020-08-08 11:13:09.493  Error: #0  /home/ke/domoticz/domoticz :  + 0x38fc96 [0x55b67db6ec96]
2020-08-08 11:13:09.493  Error: #1  /home/ke/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x2b5 [0x55b67db6f855]
2020-08-08 11:13:09.493  Error: #2  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x153c0 [0x7f1d852bd3c0]
2020-08-08 11:13:09.493  Error: #3  /lib/x86_64-linux-gnu/libpthread.so.0 : raise + 0xcb [0x7f1d852bd24b]
2020-08-08 11:13:09.493  Error: #4  /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x153c0 [0x7f1d852bd3c0]
2020-08-08 11:13:09.493  Error: #5  /lib/x86_64-linux-gnu/libpython3.8.so :  + 0x26b5a1 [0x7f1d83fb75a1]
2020-08-08 11:13:09.493  Error: #6  /lib/x86_64-linux-gnu/libpython3.8.so : PyDict_SetItem + 0x24b [0x7f1d83fb7e8b]
2020-08-08 11:13:09.493  Error: #7  /lib/x86_64-linux-gnu/libpython3.8.so : PyDict_SetItemString + 0x39 [0x7f1d83fb4019]
2020-08-08 11:13:09.493  Error: #8  /home/ke/domoticz/domoticz :  + 0x77ab5a [0x55b67df59b5a]
2020-08-08 11:13:09.493  Error: #9  /home/ke/domoticz/domoticz : Plugins::CPluginProtocolMQTT::ProcessInbound(Plugins::ReadEvent const*) + 0x8d5 [0x55b67df5d695]
2020-08-08 11:13:09.493  Error: #10 /home/ke/domoticz/domoticz : Plugins::CPluginMessageBase::Process() + 0x37 [0x55b67dae3817]
2020-08-08 11:13:09.493  Error: #11 /home/ke/domoticz/domoticz : Plugins::CPluginSystem::Do_Work() + 0xbce [0x55b67df5456e]
2020-08-08 11:13:09.493  Error: #12 /home/ke/domoticz/domoticz :  + 0xadc7af [0x55b67e2bb7af]
2020-08-08 11:13:09.493  Error: #13 /lib/x86_64-linux-gnu/libpthread.so.0 :  + 0x9609 [0x7f1d852b1609]
2020-08-08 11:13:09.493  Error: #14 /lib/x86_64-linux-gnu/libc.so.6 : clone + 0x43 [0x7f1d8505a103]

**Comment by enesbcs** [comment] 2020-08-08 15:26
Domoticz and Python version?

**Comment by siether** [comment] 2020-08-09 07:30
Python 3.8.2
Domoticz: Version: 2020.2 (build 12231)

It even crashed when I changed a device type from Default to Generic (Lamp->switch)

**Comment by enesbcs** [comment] 2020-08-17 16:41
I've tested these in an Ubuntu Linux 18.04 + Python 3.8.5 environment with Domoticz V2020.2 (build 12247).
Devices can not be added manually as they are auto detected. I've renamed and deleted them without problem (Deletion has no use as they will be autodetected again. In case you disable automatic device detection, an error message pops up in logs, but plugin works after that without problem). Also changed a Shelly Plug from Default to Generic type without any problem.
So i am unable to reproduce this bug, maybe it is not plugin related.. You can try with another Domoticz version or with a clean installation with empty database.

1. Please be advised that the last stable Domoticz version is: 2020.2.11995
You are using a beta development version.
2. Install Python 3.8 properly for plugin usage:
sudo apt install python3.8 libpython3.8 python3.8-dev

**Comment by svde** [comment] 2020-08-24 06:59
I'm running Fedora 32 x86_64, domoticz-2020.2.12271 (latest from github) and I'm also seeing crashes when adding / renaming devices.

**Comment by enesbcs** [comment] 2020-08-24 16:16
Setup:
Ubuntu 20.04.1 LTS (Focal Fossa) - Linux 5.4.0-42-generic x86_64
Python 3.8.2
Domoticz 2020.2
```

2020-08-24 16:11:24.580 Status: Domoticz V2020.2 (c)2012-2020 GizMoCuz
2020-08-24 16:11:24.583 Status: Build Hash: b63341bc0, Date: 2020-04-26 11:47:55
2020-08-24 16:11:24.672 Status: PluginSystem: Started, Python version '3.8.2'.
2020-08-24 16:11:26.682 Status: (shellymqtt) Started.
2020-08-24 16:11:27.231 Status: (shellymqtt) Initialized version 0.5.1
2020-08-24 16:11:27.232 Status: (shellymqtt) Entering work loop. 
```

I've renamed several devices, saved the changes, changed icons and still working without problem. New installation, new linux, newly installed empyt Domoticz.
"Accept new Hardware Devices" enabled in Domoticz, it is the default.

**Comment by enesbcs** [comment] 2020-08-24 16:47
Please specify the number of shelly devices and the logical ID number of the last Shelly. 255 is the upper limit for any Domoticz plugin.

**Comment by siether** [comment] 2020-08-24 20:32
I have 5 Shelly's
1 dimmer
1 shelly em
3 shelly 1's (one with temperature plugin)

Highest idx is 194

**Comment by enesbcs** [comment] 2020-08-25 15:19
Than this issue is not related to maximum device count. Could you test it with plugin version 0.5.2?

**Comment by siether** [comment] 2020-08-27 12:29
I Don't know what changed. I've updated to 0.5.2 and everything seems to be working now :-)

Bought you 3 coffees!

**Comment by enesbcs** [comment] 2020-08-27 16:16
Thanks for feedback!
In 0.5.2 i've modified device searching on all device types to use function which added 5 days ago by @pagocs 

Also added "onDeviceModified(Unit)" dummy function into plugin to handle incoming calls from Domoticz on device change, which was not needed earlier. I am not sure which Domoticz version introduced this.

**Comment by enesbcs** [comment] 2020-09-01 18:36
Closed as no further feedbacks, i hope it solved.

**Closed by enesbcs** 2020-09-01 18:36 UTC
Labels: feedback needed
