### ISSUE TITLE
Problem after updating to the last beta from domoticz

### ISSUE THREAD

**Issue by salopette** [enesbcs/Shelly_MQTT#93] opened 2021-05-08 05:57 UTC
Hello, after the last update 2 days ago, domoticz stops when Shelly or Tasmota plugin is started.

https://github.com/domoticz/domoticz/issues/4815

https://www.domoticz.com/forum/viewtopic.php?f=6&t=36236&p=274612#p274612

**Comment by JrCs** [comment] 2021-05-09 10:53
Same here with the domoticz docker image:
```
2021-05-09 12:47:44.573  Error: Shelly MQTT: Callback: Unknown execption thrown
Fatal Python error: Segmentation fault

Current thread 0x00007fe7caffd700 (most recent call first):
  File "/opt/domoticz/userdata/plugins/Shelly_MQTT/plugin.py", line 960 in onMQTTPublish
  File "/opt/domoticz/userdata/plugins/Shelly_MQTT/mqtt.py", line 176 in onMessage
  File "/opt/domoticz/userdata/plugins/Shelly_MQTT/plugin.py", line 326 in onMessage
  File "/opt/domoticz/userdata/plugins/Shelly_MQTT/plugin.py", line 1351 in onMessage
2021-05-09 12:47:44.574  Error: Domoticz(pid:1, tid:30('Shelly MQTT')) received fatal signal 11 (Segmentation fault)
2021-05-09 12:47:44.588  Error: Failed to start gdb, will use backtrace() for printing stack frame

2021-05-09 12:47:44.591  Error: #0  /opt/domoticz/domoticz :  + 0x3b1173 [0x5620e82cb173]
2021-05-09 12:47:44.591  Error: #1  /opt/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x205 [0x5620e82cbbd5]
```

**Comment by enesbcs** [comment] 2021-05-09 13:13
> 2021-05-09 12:47:44.573  Error: Shelly MQTT: Callback: Unknown execption thrown
> Fatal Python error: Segmentation fault
> 
> Current thread 0x00007fe7caffd700 (most recent call first):
>   File "/opt/domoticz/userdata/plugins/Shelly_MQTT/plugin.py", line 960 in onMQTTPublish
>   File "/opt/domoticz/userdata/plugins/Shelly_MQTT/mqtt.py", line 176 in onMessage

mqtt.py is almost the same as in the zigbee2mqtt, line 176 does this:
self.on_mqtt_message_cb(topic, message)

There are nothing i can do for this issue in plugin level, and as i see upstream Domoticz issue is closed.

**Comment by enesbcs** [comment] 2021-05-09 13:27
> Current thread 0x00007fe7caffd700 (most recent call first):
>   File "/opt/domoticz/userdata/plugins/Shelly_MQTT/plugin.py", line 960 in onMQTTPublish

Can you confirm, that your last device id in shelly_mqtt devices is lesser than 255?

**Comment by svde** [comment] 2021-05-09 13:33
I'm also experiencing this issue. With "device id" do you mean idx? Most of my shelly devices have IDX above 255.

**Comment by enesbcs** [comment] 2021-05-09 13:52
> I'm also experiencing this issue. With "device id" do you mean idx? Most of my shelly devices have IDX above 255.

Nope. IDX is Domoticz global id (at Column 1 in Devices page). "UNIT" number is the 3rd column in Devices page, and it is an integer from 1 to 255 which identifies the unit inside a Python plugin, which is independent from IDX.

**Comment by svde** [comment] 2021-05-09 14:00
OK. I don't have domoticz running, so unless I peak into the database I won't be able to find it.

Perhaps this helps:
domoticz-2021.1.**13249**-1.1.x86_64 was running good, it was started on May  6 01:49:07. This afternoon updated to 2021.1.**13252**-1.1, just 3 git commits older than the previous known good. We're now at 13253. I think it's caused by this commit: https://github.com/domoticz/domoticz/commit/c1526b1277f43bbb214b3c74d1a85685ee1056ae

**Comment by gizmocuz** [comment] 2021-05-09 14:42
the change in that commit just changes the reported ID to have the same look as on the devices page.
Besides the formatting changes, this is the actual change

```
if ((dType == pTypeTEMP) || (dType == pTypeTEMP_BARO) || (dType == pTypeTEMP_HUM) || (dType == pTypeTEMP_HUM_BARO) || (dType == pTypeBARO) || (dType == pTypeHUM) ||
		    (dType == pTypeWIND) || (dType == pTypeRAIN) || (dType == pTypeUV) || (dType == pTypeCURRENT) || (dType == pTypeCURRENTENERGY) || (dType == pTypeENERGY) ||
		    (dType == pTypeRFXMeter) || (dType == pTypeAirQuality) || (dType == pTypeRFXSensor) || (dType == pTypeP1Power) || (dType == pTypeP1Gas))
		{
			root["id"] = std_format("%04X", std::stoi(did));
		}
		else
		{
			root["id"] = did;
		}

```

This is for the internal MQTT hardware, not for any script

The only reason that this 'can' crash Domoticz, is that the 'did' is not a valid number (device_id)

for example is a plugin does not use the correct device_id values (like instead of a number, it is using a id like 'my-strange-string-id', then this can be a issue

For such plugins I would recommend to use a internal database that maps these strings to numeric id's

I added a try/catch, and in case of a invalid number value, the string value is used again

Not sure if that solves this issue...

New beta (13254) should now be available

**Comment by gizmocuz** [comment] 2021-05-10 06:25
That is correct , but it was intended as a normal number, or a hex representation ...
Okey leaving this as it is...
I have to find another way to synchronize devices between multiple Domoticz instances (and keeping the notifications/eventsystem working with them)
I have some ideas about this...
Thanks for the help everyone!

**Comment by enesbcs** [comment] 2021-05-15 16:40
Thanx for solving, closing issue now.

**Closed by enesbcs** 2021-05-15 16:40 UTC
Labels: unrelated, wontfix
