### ISSUE TITLE
Shelly 2 LED

### ISSUE THREAD

**Issue by Djac-se** [enesbcs/Shelly_MQTT#35] opened 2019-12-09 06:38 UTC
Looking for support for the LED dimmer

**Comment by KnatteAnka** [comment] 2020-01-14 20:22
I do have a shelly 2 Led but don't know what to change if needed but maybe i can test or give logs if that is necessary.

**Comment by enesbcs** [comment] 2020-01-14 22:58
Than please test it. In theory this plugin already contains support for shelly2led, but nobody has verified that is it works. Start with verbose debug mode and see if a new device is added when shelly2led started or changed its state.

**Comment by KnatteAnka** [comment] 2020-01-16 19:08
it has added the 2 channals and is showing the intensity if changed on the shelly website. 
1 but the type of dimmer is wrong (currently it is RGBWZ and one per channel)
2 then format it tries to send brightness to the shelly that is wrong

how i see the fixes:
1 set the dimmer type to only brightness (only one slider)  still one per channel
2 :  to set it successfully you have to send the brightnes to for example
shellies/Shelly2LED-1EF9D5/color/0/set
and shellies/Shelly2LED-1EF9D5/color/1/set 
with the payload:
{"brightness":"17"}

have tested with using node red and that do work 

log:
2020-01-16 19:52:18.814 Status: User: Knatte initiated a switch command (26/Shelly - Shelly2LED-1EF9D5-0-rgb/Set Level)
2020-01-16 19:52:47.867 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/0 off
2020-01-16 19:52:47.867 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/0/status {'ison': False, 'brightness': 69}
2020-01-16 19:52:47.874 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1 off
2020-01-16 19:52:47.874 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1/status {'ison': False, 'brightness': 37}

**Comment by enesbcs** [comment] 2020-01-16 20:27
For me the "shellies/Shelly2LED-1EF9D5/color/0" line creates a "Color Switch | White"  device in Domoticz as expected, i have no idea why you've got an rgbw device with current shelly_mqtt 0.3.9.

When i am changing the dim value with the slider then the "{'brightness': 42}" message sent to "shellies/Shelly2LED-1EF9D5/color/1/set" as you wrote. Please refresh the plugin first, delete existing shelly2led devices from domoticz, than show whole logs that contains startup and device creation informations.
Example Domoticz logs:

```
2020-01-16 21:13:53.055 Status: (shelly) Initialized version 0.3.9
2020-01-16 21:21:35.803 (shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1/status {'ison': False, 'brightness': 19}
2020-01-16 21:21:35.803 (shelly) Creating device 'Shelly2LED-1EF9D5-1-rgb'.
2020-01-16 21:21:35.909 (shelly) Updating device #2
2020-01-16 21:21:35.909 (shelly) nValue: 0 -> 0
2020-01-16 21:21:35.909 (shelly) sValue: -> 19
2020-01-16 21:21:35.909 (shelly - Shelly2LED-1EF9D5-1-rgb) Updating device from 0:'' to have values 0:'19'. 
2020-01-16 21:22:36.440 (shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1/set {'brightness': 42}
2020-01-16 21:22:36.337 Status: User: Admin initiated a switch command (2/shelly - Shelly2LED-1EF9D5-1-rgb/Set Level) 
```

**Comment by KnatteAnka** [comment] 2020-01-22 06:38
Everything work as intended when the plugin was updated and device removed and recreated

2020-01-22 07:35:04.853 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/0 off
2020-01-22 07:35:04.854 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/0/status {'ison': False, 'brightness': 100}
2020-01-22 07:35:04.854 (Shelly) Updating device #54
2020-01-22 07:35:04.854 (Shelly) nValue: 0 -> 0
2020-01-22 07:35:04.854 (Shelly) sValue: -> 100
2020-01-22 07:35:04.859 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1 off
2020-01-22 07:35:04.860 (Shelly) MQTT message: shellies/Shelly2LED-1EF9D5/color/1/status {'ison': False, 'brightness': 100}
2020-01-22 07:35:04.860 (Shelly) Updating device #55
2020-01-22 07:35:04.860 (Shelly) nValue: 0 -> 0
2020-01-22 07:35:04.860 (Shelly) sValue: -> 100

**Comment by enesbcs** [comment] 2020-01-22 16:36
Great news, thanks for testing it! :) Should we close this issue now?

**Comment by enesbcs** [comment] 2020-01-23 17:26
Issue is now closed as solved.

**Closed by enesbcs** 2020-01-23 17:26 UTC
Labels: device or pull requests needed
