### ISSUE TITLE
Domoticz crashes with shelly mqtt and is not starting.

### ISSUE THREAD

**Issue by Rad3d21** [enesbcs/Shelly_MQTT#13] opened 2019-06-09 08:32 UTC
Fatal Python error: Segmentation fault

Current thread 0xb5207430 (most recent call first):
  File "/usr/lib/python3.5/hashlib.py", line 103 in __get_openssl_constructor
  File "/usr/lib/python3.5/hashlib.py", line 210 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/usr/lib/python3.5/random.py", line 45 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/home/domoticz/domoticz/plugins/Shelly_MQTT/mqtt.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
  File "/home/domoticz/domoticz/plugins/Shelly_MQTT/plugin.py", line 48 in <module>
  File "<frozen importlib._bootstrap>", line 222 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 665 in exec_module
  File "<frozen importlib._bootstrap>", line 673 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 969 in _find_and_load
2019-06-09 10:28:35.991  Error: Domoticz(pid:10409, tid:10412('PluginMgr')) received fatal signal 11 (Segmentation fault)
2019-06-09 10:28:35.991  Error: siginfo address=0x28a9, address=0xb6e965b7
2019-06-09 10:28:36.023  Error: Failed to start gdb, will use backtrace() for printing stack frame

2019-06-09 10:28:36.029  Error: #0  ./domoticz() [0x2d8464]
2019-06-09 10:28:36.030  Error: #1  ./domoticz : signal_handler(int, siginfo_t*, void*) + 0x27c [0x2d8ef8]
2019-06-09 10:28:36.030  Error: #2  /lib/arm-linux-gnueabihf/libc.so.6 :  + 0x25270 [0xb6cc2270]
2019-06-09 10:28:36.030  Error: #3  /lib/arm-linux-gnueabihf/libpthread.so.0 :  + 0xe456 [0xb6e97456]
Segmentation fault

Python used by domoticz is 3.5.2 but the latest and in alternatives preferred is 3.6.2
Domoticz version 4.10717
OS Ubuntu 16.04.6 LTS Xenial

**Comment by enesbcs** [comment] 2019-06-09 19:58
interesting it looks like on your Python3 installation the random library is non-existent, which is used by the MQTT lib.

**Comment by enesbcs** [comment] 2019-06-17 19:07
Closed as no response and can not be reproduced.

**Comment by damsma** [comment] 2019-06-17 22:27
Could reproduce this, occures since a117483.

Fix:
change line 12 to:
 import secrets

change line 48 to:
        return 'Domoticz_' + str(int(time.time()))+'_'+str(secrets.choice(list(range(1000, 9999))))

**Comment by enesbcs** [comment] 2019-06-20 18:12
hashlib is a core Python function, secrets is not.

> import secrets
> ImportError: No module named 'secrets'

Current workaround for broken hashlib installation is this:

try:
 return 'Domoticz_' + str(int(time.time()))+'_'+str(random.randint(1000, 9999))
except:
 return 'Domoticz_' + str(int(time.time()))

**Comment by damsma** [comment] 2019-06-20 20:33
the try/except did not help here. importing the hashlib brings no error, but calling an function from it brings the segmentation fault, even if you use try/except.

i realize that this is will be an issue with the local python installation and has nothing to do with your code. i'm using an raspberry pi and installed python with apt-get so maybe it cound be an common issue?

python3.4
Linux raspberrypi 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

maybe you could replace this with something else that is not using hashlib?

**Comment by enesbcs** [comment] 2019-06-21 15:59
I've replaced random function with os.urandom which is not using hashlib in commit https://github.com/enesbcs/Shelly_MQTT/commit/4d522f7e1e112e8fb7aa6aa8d87d7cf76e38dd01

**Comment by damsma** [comment] 2019-06-21 18:09
Now it's working fine :)

**Comment by enesbcs** [comment] 2019-06-21 19:33
Thanks for feedback, issue is closing now.

**Closed by enesbcs** 2019-06-21 19:33 UTC
Labels: bug, feedback needed

**Comment by joba-1** [comment] 2019-08-10 16:06
Hi @enesbcs 

I had a similar problem, not being able to import random, and your workaround fixed it.
Now I found out why import failed and thought I let you know:

My distros python was too old for domoticz, so I added a newer one in /usr/local.
The new python itself was found via PATH, so it looked fine at first sight, but python could not find its external modules, like random.

For random to be found (and in general to have a sane python environment) I needed to set 2 environment variables (PYTHONHOME and PYTHONPATH) when using the new python with domoticz as follows (I added the Environment= line):

```
job4:~ > cat /etc/systemd/system/domoticz.service 
[Unit]
Description=Domoticz
Wants=nss-lookup.target
After=network.target                                                                                                                                                      
                                                                                                                                                                          
[Service]                                                                                                                                                                 
Environment="PYTHONHOME=/usr/local" "PYTHONPATH=/usr/local/lib/python3.7/site-packages:/usr/local/lib64/python3.7/lib-dynload"                                            
PIDFile=/run/domoticz/domoticz.pid                                                                                                                                        
ExecStart=/opt/domoticz/domoticz -daemon -syslog -log /var/log/domoticz.log -pidfile /run/domoticz/domoticz.pid -www 8888 -sslwww 8443                                    
ExecReload=/bin/kill -HUP $MAINPID                                                                                                                                        
ExecStop=/bin/kill -KILL $MAINPID                                                                                                                                         
User=domoticz                                                                                                                                                             
Group=domoticz                                                                                                                                                            
                                                                                                                                                                          
[Install]                                                                                                                                                                 
WantedBy=multi-user.target                                                                                                                                                
```
hope it helps - I think os.urandom is not needed then - it just worked because os module does not need to be loaded via above path variables.

I think @damsma had a similar problem since he also did not use the "standard" python version which caused nonmatching modules to be loaded
